version: '3'

services:
    bot:
        build:
            context: .
        env_file: .env
        restart: always
        volumes:
            - /root/quotes/quotes.json:/app/quotes.json
            - /root/omochao-quote-bot/text-quotes.json:/app/text-quotes.json
            - /root/omochao-quote-bot/rockyball-messages.json:/app/rockyball-messages.json
            - /root/omochao-quote-bot/rockyball-queue.json:/app/rockyball-queue.json
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        networks:
            - quotly
        command: node index.js
    mongo:
        restart: always
        image: mongo:4
        volumes:
            - mongo-volume:/data/db
        ports:
            - 127.0.0.1:27017:27017
        networks:
            - quotly
    redis:
        image: redis:7.2.5-alpine
        restart: unless-stopped
        networks:
            - quotly
    
volumes:
    mongo-volume:
        driver: 'local'

networks:
    quotly:
        external: true