name: Deploy to VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS via SSH
      run: |
        # Setup SSH key
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        
        # Add VPS to known hosts
        ssh-keyscan -p ${{ secrets.VPS_PORT || 22 }} ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
        
        # Deploy via SSH
        ssh -p ${{ secrets.VPS_PORT || 22 }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd ~/omochao-quote-bot
          
          # Pull latest changes
          git pull origin master
          
          # Rebuild and restart the bot
          docker-compose down && docker-compose up -d --build
          
          # Show final status
          docker-compose ps
          echo "Bot deployment completed at $(date)"
        EOF